# Generated by Django 4.2.7 on 2023-12-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField()),
                ('std_name', models.CharField(max_length=10)),
                ('std_course', models.CharField(max_length=10)),
            ],
        ),
    ]
