# Generated by Django 4.2.7 on 2023-12-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_std_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
