# Generated by Django 4.2.7 on 2023-12-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std_courst',
            field=models.CharField(default='pavi', max_length=10),
            preserve_default=False,
        ),
    ]
